clone_depth: 5

image:
  - Visual Studio 2017

platform:
  - x86
  - x64
  - Any CPU

install:
  - pwd
  - dir "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7"  

build_script:
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"
  - cmd: set
  - cmd: cd c:\
  - cmd: mkdir test && cd test

for:
-
  matrix:
    only:
      - platformï¼š x64
      
  test_script:
    - cmd: echo %platform%

